const arrColletion_QLV1 = [
    {
        questions: 1,
        questions__text: "Писатель, который по 10 лет писал романы,…",
        questions__answer1: "Тургенев И.С.",
        questions__answer2: "Толстой Л.Н.",
        questions__answerCorrect: "Гончаров И.А.",
        questions__img: "01_Goncharov.webp",
        uestions__nonte: "Гончаров Иван Александрович",
    },
    {
        questions: 2,
        questions__text: "Писатель, который свои пьесы озаглавил русскими пословицами?",
        questions__answer1: "Тургенев И.С.",
        questions__answer2: "Некрасов Н.А.",
        questions__answerCorrect: "Островский А.Н.",
        questions__img: "02_Ostrivsky.webp",
        uestions__nonte: "Островский Александр Николаевич",
    },
    {
        questions: 3,
        questions__text: "Русский писатель, который любил знаменитую французскую певицу, посвятив ей свою жизнь…",
        questions__answer1: "Некрасов Н.А.",
        questions__answer2: "Гончаров И.А.",
        questions__answerCorrect: "Тургенев И.С.",
        questions__img: "",
        uestions__nonte: "Тургенев Иван Сергеевич и Полина Виардо",
    },
    {
        questions: 4,
        questions__text: "Русский поэт, который  по линии отца и матери был немцем…",
        questions__answer1: "Тютчев Ф.И.",
        questions__answer2: "Некрасов Н.А.",
        questions__answerCorrect: "Фет А.А.",
        questions__img: "",
        uestions__nonte: "Фет Афанасий Афанасьевич",
    },
    {
        questions: 5,
        questions__text: "Писатель, который создавал обличительные сказки",
        questions__answer1: "Островский А.Н.",
        questions__answer2: "Толстой Л.Н.",
        questions__answerCorrect: "Салтыков-Щедрин М.Е.",
        questions__img: "05_Shedrin.webp",
        uestions__nonte: "Фет Афанасий Афанасьевич",
    },
    {
        questions: 6,
        questions__text: "Русский поэт, посвящавший поэмы декабристам…",
        questions__answer1: "Фет А.А.",
        questions__answer2: "Тютчев Ф.И.",
        questions__answerCorrect: "Некрасов Н.А.",
        questions__img: "Nekrasov.webp",
        uestions__nonte: "Николай Алексеевич Некрасов",
    },
    {
        questions: 7,
        questions__text: "Писатель, считавший, что счастье можно добиться лишь через смирение и веру в Бога",
        questions__answer1: "Толстой Л.Н.",
        questions__answer2: "Тургенев И.С.",
        questions__answerCorrect: "Достоевский М.Ф.",
        questions__img: ".webp",
        uestions__nonte: "",
    },
    {
        questions: 8,
        questions__text: "Родовое имение Л.Н. Толстого…",
        questions__answer1: "Спасское -Лутовиново",
        questions__answer2: "Лысые Горы",
        questions__answerCorrect: "Ясная Поляна",
        questions__img: ".webp",
        uestions__nonte: "Ясная Поляна",
    },
    {
        questions: 9,
        questions__text: "Роман И.А.Гончарова…",
        questions__answer1: "«Отцы и дети»",
        questions__answer2: "«Идиот»",
        questions__answerCorrect: "«Обыкновенная история»",
        questions__img: ".webp",
        uestions__nonte: "Обыкновенная история",
    },
    {
        questions: 10,
        questions__text: "Подлинная фамилия Салтыкова – Щедрина…",
        questions__answer1: "Салтыков - Щедрин.",
        questions__answer2: "Щедрин",
        questions__answerCorrect: "Салтыков",
        questions__img: ".webp",
        uestions__nonte: "Салтыков",
    },
    {
        questions: 11,
        questions__text: "Фамилия русского писателя, которого  называли «Колумб Замоскворечья»",
        questions__answer1: "Щедрин М.Е.",
        questions__answer2: "Тургенев И.С.",
        questions__answerCorrect: "Островский А.Н.",
        questions__img: ".webp",
        uestions__nonte: "Островский Александр Николаевич",
    },
    {
        questions: 12,
        questions__text: "Фамилия поэта, которому принадлежат слова «Поэтом можешь ты не быть, а гражданином быть обязан»",
        questions__answer1: "Фет А.А.",
        questions__answer2: "Тютчев Ф.И.",
        questions__answerCorrect: "Некрасов Н.А.",
        questions__img: ".webp",
        uestions__nonte: "Николай Алексеевич Некрасов",
    },
        {
        questions: 13,
        questions__text: "Писатель, принимавший участие в обороне Севастополя",
        questions__answer1: "Щедрин М.Е.",
        questions__answer2: "Достоевский Ф.М.",
        questions__answerCorrect: "Толстой Л.Н.",
        questions__img: ".webp",
        uestions__nonte: "Лев Николаевич Толстой",
    },
        {
        questions: 14,
        questions__text: "Писатель, совершивший поездку на остров Сахалин",
        questions__answer1: "Гончаров И.А.",
        questions__answer2: "Достоевский Ф.М.",
        questions__answerCorrect: "Чехов А.П.",
        questions__img: ".webp",
        uestions__nonte: "Антон Павлович Чехов",
    },
        {
        questions: 15,
        questions__text: "Фамилия писателя, которому знакомы нары Омского острога",
        questions__answer1: "Щедрин М.Е.",
        questions__answer2: "Некрасов Н.А.",
        questions__answerCorrect: "Достоевский Ф.М",
        questions__img: ".webp",
        uestions__nonte: "Фёдор Михайлович Достоевский",
    },
]