const arrColletion = [
    {
        questions: 1,
        questions__db: 1,
        questions__text: "Писатель, который по 10 лет писал романы,…",
        questions__answer1: "Тургенев И.С.",
        questions__answer2: "Толстой Л.Н.",
        questions__answerCorrect: "Гончаров И.А.",
        questions__nonte: "Иван Александрович Гончаров — русский писатель и литературный критик. Автор трёх романов — «Обломов», «Обрыв» и «Обыкновенная история».",
    },
    {
        questions: 2,
        questions__db: 1,
        questions__text: "Писатель, который свои пьесы озаглавил русскими пословицами?",
        questions__answer1: "Тургенев И.С.",
        questions__answer2: "Некрасов Н.А.",
        questions__answerCorrect: "Островский А.Н.",
        questions__nonte: "Александр Николаевич Островский — русский драматург, творчество которого стало важнейшим этапом развития русского национального театра.",
    },
    {
        questions: 3,
        questions__db: 1,
        questions__text: "Русский писатель, который любил знаменитую французскую певицу, посвятив ей свою жизнь…",
        questions__answer1: "Некрасов Н.А.",
        questions__answer2: "Гончаров И.А.",
        questions__answerCorrect: "Тургенев И.С.",
        questions__nonte: "Тургенев Иван Сергеевич и Полина Виардо",
    },
    {
        questions: 4,
        questions__db: 1,
        questions__text: "Русский поэт, который  по линии отца и матери был немцем…",
        questions__answer1: "Тютчев Ф.И.",
        questions__answer2: "Некрасов Н.А.",
        questions__answerCorrect: "Фет А.А.",
        questions__nonte: "Афанасий Афанасьевич Фет (первые 14 и последние 19 лет жизни официально носил фамилию Шеншин) — русский поэт-лирик и переводчик, прозаик, мемуарист, член-корреспондент Петербургской Академии Наук.",
    },
    {
        questions: 5,
        questions__db: 1,
        questions__text: "Писатель, который создавал обличительные сказки",
        questions__answer1: "Островский А.Н.",
        questions__answer2: "Толстой Л.Н.",
        questions__answerCorrect: "Салтыков-Щедрин М.Е.",
        questions__nonte: "Михаил Евграфович Салтыков-Щедрин (настоящая фамилия — Салтыков, псевдоним — Николай Щедрин) — русский писатель, один из наиболее известных сатириков XIX века, журналист, государственный деятель.",
    },
    {
        questions: 6,
        questions__db: 1,
        questions__text: "Русский поэт, посвящавший поэмы декабристам…",
        questions__answer1: "Фет А.А.",
        questions__answer2: "Тютчев Ф.И.",
        questions__answerCorrect: "Некрасов Н.А.",
        questions__nonte: "Николай Алексеевич Некрасов — русский поэт, прозаик и публицист, классик русской литературы.",
    },
    {
        questions: 7,
        questions__db: 1,
        questions__text: "Писатель, считавший, что счастье можно добиться лишь через смирение и веру в Бога",
        questions__answer1: "Толстой Л.Н.",
        questions__answer2: "Тургенев И.С.",
        questions__answerCorrect: "Достоевский М.Ф.",
        questions__nonte: "Фёдор Михайлович Достоевский — русский писатель, мыслитель, философ и публицист.",
    },
    {
        questions: 8,
        questions__db: 1,
        questions__text: "Родовое имение Л.Н. Толстого…",
        questions__answer1: "Спасское -Лутовиново",
        questions__answer2: "Лысые Горы",
        questions__answerCorrect: "Ясная Поляна",
        questions__nonte: "«Ясная Поляна» — музей-усадьба в Щёкинском районе Тульской области (в 14 км к юго-западу от Тулы).",
    },
    {
        questions: 9,
        questions__db: 1,
        questions__text: "Роман И.А.Гончарова…",
        questions__answer1: "«Отцы и дети»",
        questions__answer2: "«Идиот»",
        questions__answerCorrect: "«Обыкновенная история»",
        questions__nonte: "«Обыкновенная история» — первый роман русского писателя Ивана Александровича Гончарова, опубликованный в 1847 году в журнале «Современник». Иногда его объединяют в неформальную трилогию с последующими романами «Обломов» и «Обрыв».",
    },
    {
        questions: 10,
        questions__db: 1,
        questions__text: "Подлинная фамилия Салтыкова – Щедрина…",
        questions__answer1: "Салтыков - Щедрин.",
        questions__answer2: "Щедрин",
        questions__answerCorrect: "Салтыков",
        questions__nonte: "Салтыков",
    },
    {
        questions: 11,
        questions__db: 1,
        questions__text: "Фамилия русского писателя, которого  называли «Колумб Замоскворечья»",
        questions__answer1: "Щедрин М.Е.",
        questions__answer2: "Тургенев И.С.",
        questions__answerCorrect: "Островский А.Н.",
        questions__nonte: "Александр Николаевич Островский — русский драматург, творчество которого стало важнейшим этапом развития русского национального театра.",
    },
    {
        questions: 12,
        questions__db: 1,
        questions__text: "Фамилия поэта, которому принадлежат слова «Поэтом можешь ты не быть, а гражданином быть обязан»",
        questions__answer1: "Фет А.А.",
        questions__answer2: "Тютчев Ф.И.",
        questions__answerCorrect: "Некрасов Н.А.",
        questions__nonte: "Николай Алексеевич Некрасов — русский поэт, прозаик и публицист, классик русской литературы",
    },
    {
        questions: 13,
        questions__db: 1,
        questions__text: "Писатель, принимавший участие в обороне Севастополя",
        questions__answer1: "Щедрин М.Е.",
        questions__answer2: "Достоевский Ф.М.",
        questions__answerCorrect: "Толстой Л.Н.",
        questions__nonte: "Лев Николаевич Толстой — русский писатель, публицист, философ и общественный деятель, граф",
    },
    {
        questions: 14,
        questions__db: 1,
        questions__text: "Писатель, совершивший поездку на остров Сахалин",
        questions__answer1: "Гончаров И.А.",
        questions__answer2: "Достоевский Ф.М.",
        questions__answerCorrect: "Чехов А.П.",
        questions__nonte: "Антон Павлович Чехов — русский писатель, прозаик, драматург, публицист, врач, общественный деятель в сфере благотворительности. Классик мировой литературы. Почётный академик Императорской академии наук по разряду изящной словесности (1900–1902).",
    },
    {
        questions: 15,
        questions__db: 1,
        questions__text: "Фамилия писателя, которому знакомы нары Омского острога",
        questions__answer1: "Щедрин М.Е.",
        questions__answer2: "Некрасов Н.А.",
        questions__answerCorrect: "Достоевский Ф.М",
        questions__nonte: "Фёдор Михайлович Достоевский — русский писатель, мыслитель, философ и публицист.",
    },

    // ВТОРОЙ ВОПРОС=======================================================================================================================
    {
        questions: 1,
        questions__db: 2,
        questions__text: "Герой, лежанье которого «... как у лентяя, ... было его нормальным состоянием»…",
        questions__answer1: "Евгений Васильевич Базаров",
        questions__answer2: "Павел Петрович Кирсанов",
        questions__answerCorrect: "Илья Ильич Обломов",
        questions__nonte: "Илья Ильич Обломов - главный герой романа И. А. Гончарова «Обломов». Это молодой дворянин тридцати с небольшим лет. От его фамилии произошло слово «обломовщина», ставшее нарицательным, и обозначающее застой.",
    },
    {
        questions: 2,
        questions__db: 2,
        questions__text: "Герой, не признававший авторитетов и отрицающий всё,…",
        questions__answer1: "Родион Раскольников",
        questions__answer2: "Андрей Болконский",
        questions__answerCorrect: "Евгений Базаров",
        questions__nonte: "Евгений Васильевич Базаров — персонаж романа И.С. Тургенева «Отцы и дети», студент-нигилист",
    },
    {
        questions: 3,
        questions__db: 2,
        questions__text: "Основное содержание романа «Преступление и наказание»…",
        questions__answer1: "Изображение преступления",
        questions__answer2: "Описание подготовки к убийству",
        questions__answerCorrect: "Описание нравственных последствий преступления",
        questions__nonte: "Описание нравственных последствий преступления",
    },
    {
        questions: 4,
        questions__db: 2,
        questions__text: "Героиня, которая, ворча, со свету сживала: «…ведь от любви родители и строги - то к вам бывают, от любви вас бранят - то, всё думают добру научить»-….",
        questions__answer1: "Агафья Пшеницына   ",
        questions__answer2: "Ольга Сергеевна Ильинская",
        questions__answerCorrect: "Марфа Игнатьевна Кабанова.",
        questions__nonte: "Марфа Игнатьевна Кабанова -  Является главой купеческого семейства Кабановых, вдова.",
    },
    {
        questions: 5,
        questions__db: 2,
        questions__text: "Героиня, мечтавшая: «…вылетела бы в поле и летала бы с василька на василёк по ветру, как бабочка»…",
        questions__answer1: "Анна Сергеевна Одинцова",
        questions__answer2: "Ольга Сергеевна Ильинская",
        questions__answerCorrect: "Екатерина Петровна Кабанова",
        questions__nonte: "Екатерина Петровна Кабанова",
    },
    {
        questions: 6,
        questions__db: 2,
        questions__text: "Герой,  живший «по принципам» аристократизма,…",
        questions__answer1: "Илья Андреевич Ростов",
        questions__answer2: "Николай Андреевич Болконский",
        questions__answerCorrect: "Павел Петрович Кирсанов",
        questions__nonte: "Павел Петрович Кирсанов",
    },
    {
        questions: 7,
        questions__db: 2,
        questions__text: "Герой, хотевший осчастливить человечество,…",
        questions__answer1: "Базаров Е.В.",
        questions__answer2: "Болконский Н.А.",
        questions__answerCorrect: "Раскольников Р.Р.",
        questions__nonte: "Родион Романович Раскольников",
    },
    {
        questions: 8,
        questions__db: 2,
        questions__text: "Герой:  «... толстый молодой человек со стриженою головой, в очках, светлых панталонах по тогдашней моде, с высоким жабо и в коричневом фраке» - это…",
        questions__answer1: "Илья Ильич Обломов",
        questions__answer2: "Савел Прокофьевич Дикой",
        questions__answerCorrect: "Пьер Кириллович Безухов",
        questions__nonte: "Пьер Кириллович Безухов",
    },
    {
        questions: 9,
        questions__db: 2,
        questions__text: "Девушка:  «черноглазая, с большим ртом, некрасивая, живая девочка, с своими детскими открытыми плечиками ... сбившимися назад чёрными кудрями, тоненькими оголёнными и маленькими ножками» - это...",
        questions__answer1: "Лицемерие",
        questions__answer2: "Легкомыслие",
        questions__answerCorrect: "Жертвенность",
        questions__img: ".webp",
        questions__nonte: "Жертвенность Сони Мармеладовой",
    },
    {
        questions: 10,
        questions__db: 2,
        questions__text: "В этом произведении  можно задохнуться от пыли, грязи, жары- …",
        questions__answer1: "Гончаров И.А. «Обломов»",
        questions__answer2: "Островский Н.А. «Гроза»",
        questions__answerCorrect: "Достоевский Ф.М. «Преступление и наказание»",
        questions__img: ".webp",
        questions__nonte: "Достоевский Ф.М. «Преступление и наказание»",
    },
    {
        questions: 11,
        questions__db: 2,
        questions__text: "Качество характера Сони Мармеладовой",
        questions__answer1: "Лицемерие",
        questions__answer2: "Легкомыслие",
        questions__answerCorrect: "Жертвенность",
        questions__img: ".webp",
        questions__nonte: "Жертвенность",
    },
    {
        questions: 12,
        questions__db: 2,
        questions__text: "Произведение, в котором герой свою жизнь посвятил мечте",
        questions__answer1: "«Гроза»",
        questions__answer2: "«Обломов»",
        questions__answerCorrect: "«Крыжовник»",
        questions__img: ".webp",
        questions__nonte: "«Крыжовник»",
    },
    {
        questions: 13,
        questions__db: 2,
        questions__text: "Теория Раскольникова - это",
        questions__answer1: "разделение людей на разряды в соответствии их социальной принадлежности.",
        questions__answer2: "строгое научное разделение людей на разряды ",
        questions__answerCorrect: "разделение людей на  разряды: материал и собственно люди",
        questions__img: ".webp",
        questions__nonte: "",
    },
    {
        questions: 14,
        questions__db: 2,
        questions__text: "Героиня, на образе которой писатель решает проблему «истинной красоты человека»",
        questions__answer1: "Катерина Кабанова",
        questions__answer2: "Наташа Ростова",
        questions__answerCorrect: "Соня Мармеладова",
        questions__img: ".webp",
        questions__nonte: "",
    },
    {
        questions: 15,
        questions__db: 2,
        questions__text: "Произведение, в котором герой любил произносит фразу: «Как бы чего не вышло»",
        questions__answer1: "«Обломов»",
        questions__answer2: "«Преступление и наказание»",
        questions__answerCorrect: "«Человек в футляре»",
        questions__img: ".webp",
        questions__nonte: "",
    },

    // ТРЕТИЙ ВОПРОС=======================================================================================================================
    {
        questions: 1,
        questions__db: 3,
        questions__text: "Рассказ «Человек футляре» входит в цикл",
        questions__answer1: "«Темные аллеи»",
        questions__answer2: "«Записки охотника»",
        questions__answerCorrect: "«Маленькая трилогия»",
        questions__nonte: "",
    },
    {
        questions: 2,
        questions__db: 3,
        questions__text: "Жанр произведения – роман-эпопея",
        questions__answer1: "«Отцы и дети» Тургенев И.С. ",
        questions__answer2: "«Преступление и наказание» Достоевский М.Ф.",
        questions__answerCorrect: "«Война и мир» Толстой Л.Н. ",
        questions__nonte: "",
    },
    {
        questions: 3,
        questions__db: 3,
        questions__text: "Писатель, который писал «стихи в прозе»…",
        questions__answer1: "Толстой Л.Н.",
        questions__answer2: "Некрасов Н.А. ",
        questions__answerCorrect: "Тургенев И.С.",
        questions__nonte: "Иван Сергеевич Тургенев",
    },
    {
        questions: 4,
        questions__db: 3,
        questions__text: "Произведение, в котором есть эпилог,…",
        questions__answer1: "«Обломов»",
        questions__answer2: "«Преступление и наказание»",
        questions__answerCorrect: "«Война и мир»",
        questions__nonte: "",
    },
    {
        questions: 5,
        questions__db: 3,
        questions__text: "Русский писатель-сатирик…",
        questions__answer1: "Островский А.Н.",
        questions__answer2: "Гончаров И.А.",
        questions__answerCorrect: "Салтыков-Щедрин М.Е.",
        questions__nonte: "",
    },
    {
        questions: 6,
        questions__db: 3,
        questions__text: "Автор -  «отец русской драматургии, создатель русского театра»…",
        questions__answer1: "Тургенев И.С.",
        questions__answer2: "Некрасов Н.А.",
        questions__answerCorrect: "Островский А.Н.",
        questions__nonte: "",
    },
    {
        questions: 7,
        questions__db: 3,
        questions__text: "Роман в стихах …",
        questions__answer1: "«Русские женщины»",
        questions__answer2: "«Русские женщины»",
        questions__answerCorrect: "«Евгений Онегин»",
        questions__nonte: "",
    },
    {
        questions: 8,
        questions__db: 3,
        questions__text: "Жанр лирики…",
        questions__answer1: "новелла",
        questions__answer2: "рассказ",
        questions__answerCorrect: "элегия",
        questions__nonte: "",
    },
    {
        questions: 9,
        questions__db: 3,
        questions__text: "Поэма - …",
        questions__answer1: "«Евгений Онегин»",
        questions__answer2: "«Ревизор»",
        questions__answerCorrect: "«Мертвые души»",
        questions__nonte: "",
    },
    {
        questions: 10,
        questions__db: 3,
        questions__text: "Род литературы…",
        questions__answer1: "новелла",
        questions__answer2: "фольклор",
        questions__answerCorrect: "эпос",
        questions__nonte: "",
    },
    {
        questions: 11,
        questions__db: 3,
        questions__text: "Элемент композиции…",
        questions__answer1: "сюжет",
        questions__answer2: "проблематика",
        questions__answerCorrect: "экспозиция",
        questions__nonte: "",
    },
    {
        questions: 12,
        questions__db: 3,
        questions__text: "Поэт «чистого искусства» …",
        questions__answer1: "И.С. Тургенев",
        questions__answer2: "Н.А. Некрасов",
        questions__answerCorrect: "Ф.И. Тютчев",
        questions__nonte: "",
    },
    {
        questions: 13,
        questions__db: 3,
        questions__text: "Имя писателя, который внес большой вклад в развитие русского языка и русской литературы за рубежом…",
        questions__answer1: "Л.Н. Толстой",
        questions__answer2: "Ф.М. Достоевский",
        questions__answerCorrect: "И.С. Тургенев",
        questions__nonte: "",
    },
    {
        questions: 14,
        questions__db: 3,
        questions__text: "Основная тема цикла рассказов «Записки охотника»…",
        questions__answer1: "Тема природы",
        questions__answer2: "Тема крепостного права",
        questions__answerCorrect: "Человек и животные",
        questions__nonte: "",
    },
    {
        questions: 15,
        questions__db: 3,
        questions__text: "Задача литературы ….",
        questions__answer1: "Изображать художественных героев",
        questions__answer2: "Развлекать читателей",
        questions__answerCorrect: "Отражать действительность",
        questions__nonte: "",
    },
]