const arrColletion = [
    {
        questions: 1,
        questions__text: "Писатель, который по 10 лет писал романы,…",
        questions__answer1: "Тургенев И.С.",
        questions__answer2: "Толстой Л.Н.",
        questions__answerCorrect: "Гончаров И.А.",
        questions__img: "01_Goncharov.webp",
        uestions__nonte: "Гончаров Иван Александрович",
    },
    {
        questions: 2,
        questions__text: "Писатель, который свои пьесы озаглавил русскими пословицами?",
        questions__answer1: "Тургенев И.С.",
        questions__answer2: "Некрасов Н.А.",
        questions__answerCorrect: "Островский А.Н.",
        questions__img: "02_Ostrivsky.webp",
        uestions__nonte: "Островский Александр Николаевич",
    },
    {
        questions: 3,
        questions__text: "Русский писатель, который любил знаменитую французскую певицу, посвятив ей свою жизнь…",
        questions__answer1: "Некрасов Н.А.",
        questions__answer2: "Гончаров И.А.",
        questions__answerCorrect: "Тургенев И.С.",
        questions__img: "",
        uestions__nonte: "Тургенев Иван Сергеевич и Полина Виардо",
    },
    {
        questions: 4,
        questions__text: "Русский поэт, который  по линии отца и матери был немцем…",
        questions__answer1: "Тютчев Ф.И.",
        questions__answer2: "Некрасов Н.А.",
        questions__answerCorrect: "Фет А.А.",
        questions__img: "",
        uestions__nonte: "Фет Афанасий Афанасьевич",
    },
    {
        questions: 5,
        questions__text: "Писатель, который создавал обличительные сказки",
        questions__answer1: "Островский А.Н.",
        questions__answer2: "Толстой Л.Н.",
        questions__answerCorrect: "Салтыков-Щедрин М.Е.",
        questions__img: "",
        uestions__nonte: "Фет Афанасий Афанасьевич",
    },
    {
        questions: 6,
        questions__text: "Русский поэт, посвящавший поэмы декабристам…",
        questions__answer1: "Островский А.Н.",
        questions__answer2: "Толстой Л.Н.",
        questions__answerCorrect: "Салтыков-Щедрин М.Е.",
        questions__img: "",
        uestions__nonte: "Фет Афанасий Афанасьевич",
    },
]