const arrColletion_QLV2 = [
    {
        questions: 1,
        questions__text: "Герой, лежанье которого «... как у лентяя, ... было его нормальным состоянием»…",
        questions__answer1: "Евгений Васильевич Базаров",
        questions__answer2: "Павел Петрович Кирсанов",
        questions__answerCorrect: "Илья Ильич Обломов",
        questions__img: ".webp",
        uestions__nonte: "Илья Ильич Обломов",
    },
    {
        questions: 2,
        questions__text: "Герой, не признававший авторитетов и отрицающий всё,…",
        questions__answer1: "Родион Раскольников",
        questions__answer2: "Андрей Болконский",
        questions__answerCorrect: "Евгений Базаров",
        questions__img: ".webp",
        uestions__nonte: "Евгений Базаров",
    },
    {
        questions: 3,
        questions__text: "Основное содержание романа «Преступление и наказание»…",
        questions__answer1: "Изображение преступления",
        questions__answer2: "Описание подготовки к убийству",
        questions__answerCorrect: "Описание нравственных последствий преступления",
        questions__img: ".webp",
        uestions__nonte: "",
    },
    {
        questions: 4,
        questions__text: "Героиня, которая, ворча, со свету сживала: «…ведь от любви родители и строги - то к вам бывают, от любви вас бранят - то, всё думают добру научить»-….",
        questions__answer1: "Агафья Пшеницына   ",
        questions__answer2: "Ольга Сергеевна Ильинская",
        questions__answerCorrect: "Марфа Игнатьевна Кабанова.",
        questions__img: ".webp",
        uestions__nonte: "Марфа Игнатьевна Кабанова.",
    },
    {
        questions: 5,
        questions__text: "Героиня, мечтавшая: «…вылетела бы в поле и летала бы с василька на василёк по ветру, как бабочка»…",
        questions__answer1: "Анна Сергеевна Одинцова",
        questions__answer2: "Ольга Сергеевна Ильинская",
        questions__answerCorrect: "Екатерина Петровна Кабанова",
        questions__img: ".webp",
        uestions__nonte: "Екатерина Петровна Кабанова",
    },
    {
        questions: 6,
        questions__text: "Герой,  живший «по принципам» аристократизма,…",
        questions__answer1: "Илья Андреевич Ростов",
        questions__answer2: "Николай Андреевич Болконский",
        questions__answerCorrect: "Павел Петрович Кирсанов",
        questions__img: ".webp",
        uestions__nonte: "Павел Петрович Кирсанов",
    },
    {
        questions: 7,
        questions__text: "Герой, хотевший осчастливить человечество,…",
        questions__answer1: "Базаров Е.В.",
        questions__answer2: "Болконский Н.А.",
        questions__answerCorrect: "Раскольников Р.Р.",
        questions__img: ".webp",
        uestions__nonte: "Родион Романович Раскольников",
    },
    {
        questions: 8,
        questions__text: "Герой:  «... толстый молодой человек со стриженою головой, в очках, светлых панталонах по тогдашней моде, с высоким жабо и в коричневом фраке» - это…",
        questions__answer1: "Илья Ильич Обломов",
        questions__answer2: "Савел Прокофьевич Дикой",
        questions__answerCorrect: "Пьер Кириллович Безухов",
        questions__img: ".webp",
        uestions__nonte: "Пьер Кириллович Безухов",
    },
    {
        questions: 9,
        questions__text: "Девушка:  «черноглазая, с большим ртом, некрасивая, живая девочка, с своими детскими открытыми плечиками ... сбившимися назад чёрными кудрями, тоненькими оголёнными и маленькими ножками» - это...",
        questions__answer1: "Лицемерие",
        questions__answer2: "Легкомыслие",
        questions__answerCorrect: "Жертвенность",
        questions__img: ".webp",
        uestions__nonte: "Жертвенность Сони Мармеладовой",
    },
    {
        questions: 10,
        questions__text: "Произведение, в котором герой свою жизнь посвятил мечте",
        questions__answer1: "«Гроза»",
        questions__answer2: "«Обломов»",
        questions__answerCorrect: "«Крыжовник»",
        questions__img: ".webp",
        uestions__nonte: "",
    },
    {
        questions: 11,
        questions__text: "Теория Раскольникова - это",
        questions__answer1: "разделение людей на разряды в соответствии их социальной принадлежности.",
        questions__answer2: "строгое научное разделение людей на разряды ",
        questions__answerCorrect: "разделение людей на  разряды: материал и собственно люди",
        questions__img: ".webp",
        uestions__nonte: "",
    },
    {
        questions: 12,
        questions__text: "",
        questions__answer1: "",
        questions__answer2: "",
        questions__answerCorrect: "",
        questions__img: ".webp",
        uestions__nonte: "",
    },
    {
        questions: 13,
        questions__text: "",
        questions__answer1: "",
        questions__answer2: "",
        questions__answerCorrect: "",
        questions__img: ".webp",
        uestions__nonte: "",
    },
    {
        questions: 14,
        questions__text: "",
        questions__answer1: "",
        questions__answer2: "",
        questions__answerCorrect: "",
        questions__img: ".webp",
        uestions__nonte: "",
    },
    {
        questions: 15,
        questions__text: "",
        questions__answer1: "",
        questions__answer2: "",
        questions__answerCorrect: "",
        questions__img: ".webp",
        uestions__nonte: "",
    },
]